# Generated by Django 3.2.2 on 2022-04-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bogiereceiveregister',
            name='RecDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
