# Generated by Django 3.2.2 on 2022-04-18 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bogie', '0002_bogiereceiveregister_recdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bogie',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FabBogieRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('RepDate', models.DateField(blank=True, null=True)),
                ('BogieType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='BogieTypeFab', to='bogie.bogie')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='railpointuser4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BogieDispatchRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('DispDate', models.DateField(blank=True, null=True)),
                ('BogieType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='BogieTypeDisp', to='bogie.bogie')),
                ('PlaceName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='BogieDispFrom', to='bogie.railpoint')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='railpointuser3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
