# Generated by Django 3.2.2 on 2022-04-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogie', '0003_auto_20220418_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabbogieregister',
            name='RepDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
