# Generated by Django 3.2.2 on 2022-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogie', '0004_alter_fabbogieregister_repdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabbogieregister',
            name='RepDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
