# Generated by Django 3.2.2 on 2022-04-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogie', '0005_alter_fabbogieregister_repdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bogie',
            name='SickQuantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
