# Generated by Django 3.2.2 on 2022-04-18 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DPC0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DPCName', models.CharField(max_length=100, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('POHDate', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dpcauth0', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DPCArea0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DPCArea', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DPCDef0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DPCDef', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DPCSection0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MC0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCName', models.CharField(max_length=100, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('POHDate', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mcauth0', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCArea0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCArea', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MCDef0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCDef', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MCSection0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TC0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCName', models.CharField(max_length=100, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('POHDate', models.DateField(blank=True, null=True)),
                ('Memu', models.BooleanField(blank=True, default='False')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tcauth0', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TCArea0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCCArea', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TCDef0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCDef', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TCSection0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TCRemark0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('POHDate', models.DateField(blank=True, null=True)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TCSection10', to='defi2.tcsection0')),
                ('TCDef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TCDef10', to='defi2.tcdef0')),
                ('TCDefArea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TCArea10', to='defi2.tcarea0')),
                ('TCName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TCName10', to='defi2.tc0')),
            ],
        ),
        migrations.CreateModel(
            name='MCRemark0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('POHDate', models.DateField(blank=True, null=True)),
                ('MCDef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MCDef1', to='defi2.mcdef0')),
                ('MCDefArea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MCArea1', to='defi2.mcarea0')),
                ('MCName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MCName10', to='defi2.mc0')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MCSection10', to='defi2.mcsection0')),
            ],
        ),
        migrations.CreateModel(
            name='DPCRemark0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('POHDate', models.DateField(blank=True, null=True)),
                ('DPCDef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DPCDef10', to='defi2.dpcdef0')),
                ('DPCDefArea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DPCArea10', to='defi2.dpcarea0')),
                ('DPCName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DPCName10', to='defi2.dpc0')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DPCSection10', to='defi2.dpcsection0')),
            ],
        ),
    ]
