# Generated by Django 3.2.6 on 2022-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerWheelDispatchedCARSHEDGZB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WheelSetNo', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('NotAdded', 'NotAdded'), ('DMC', 'DMC')], default='NotAdded', max_length=11)),
                ('Date', models.DateField(blank=True, null=True)),
                ('WorkOrderNo', models.CharField(max_length=100, unique=True)),
                ('WorkDone', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='registerWheelDispatchedCDOLKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WheelSetNo', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('NotAdded', 'NotAdded'), ('BCN', 'BCN'), ('ICF', 'ICF')], default='NotAdded', max_length=11)),
                ('Date', models.DateField(blank=True, null=True)),
                ('WorkOrderNo', models.CharField(max_length=100, unique=True)),
                ('WorkDone', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='registerWheelDispatchedDSLAMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WheelSetNo', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('NotAdded', 'NotAdded'), ('WAP4', 'WAP4'), ('WAP7', 'WAP7'), ('WDP4', 'WDP4')], default='NotAdded', max_length=11)),
                ('Date', models.DateField(blank=True, null=True)),
                ('WorkOrderNo', models.CharField(max_length=100, unique=True)),
                ('WorkDone', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='registerWheelDispatchedDSLTKD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WheelSetNo', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('NotAdded', 'NotAdded'), ('WAP4', 'WAP4'), ('WAP7', 'WAP7'), ('WDP4', 'WDP4')], default='NotAdded', max_length=11)),
                ('Date', models.DateField(blank=True, null=True)),
                ('WorkOrderNo', models.CharField(max_length=100, unique=True)),
                ('WorkDone', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='registerWheelDispatchedELSSRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WheelSetNo', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('NotAdded', 'NotAdded'), ('WAP4', 'WAP4'), ('WAP7', 'WAP7'), ('WDP4', 'WDP4')], default='NotAdded', max_length=11)),
                ('Date', models.DateField(blank=True, null=True)),
                ('WorkOrderNo', models.CharField(max_length=100, unique=True)),
                ('WorkDone', models.CharField(max_length=500)),
            ],
        ),
    ]
