# Generated by Django 3.2.2 on 2022-04-28 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MnP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineName', models.CharField(max_length=100, unique=True)),
                ('UpdateDate', models.DateField(blank=True, null=True)),
                ('ManufacDate', models.DateField(blank=True, null=True)),
                ('EsttDate', models.DateField(blank=True, null=True)),
                ('LastOverhaulDate', models.DateField(blank=True, null=True)),
                ('LastCalibDate', models.DateField(blank=True, null=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='uploadsMNPpics/%Y/%m/%d/')),
                ('MnPStatus', models.BooleanField(blank=True, default='False')),
            ],
        ),
        migrations.CreateModel(
            name='MNPSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MNPShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MNPType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MnPRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('commentfile', models.FileField(blank=True, null=True, upload_to='uploadsMNPRemark/%Y/%m/%d/')),
                ('MachineName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mnpmachrem', to='mnp.mnp')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mnpremauth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mnp',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MNPSection', to='mnp.mnpsection'),
        ),
        migrations.AddField(
            model_name='mnp',
            name='Shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MNPShop', to='mnp.mnpshop'),
        ),
        migrations.AddField(
            model_name='mnp',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MNPType', to='mnp.mnptype'),
        ),
        migrations.AddField(
            model_name='mnp',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mnpauth', to=settings.AUTH_USER_MODEL),
        ),
    ]
