# Generated by Django 3.2.2 on 2022-04-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mnp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnpsection',
            name='Shop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MNPSecShop', to='mnp.mnpshop'),
            preserve_default=False,
        ),
    ]
