# Generated by Django 3.2.2 on 2022-04-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnp', '0002_mnpsection_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnp',
            name='MachineName',
            field=models.CharField(max_length=100),
        ),
    ]
