# Generated by Django 3.2.2 on 2022-04-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnp', '0003_alter_mnp_machinename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnp',
            name='pic',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='uploadsMNPpics/%Y/%m/%d/'),
        ),
    ]
