# Generated by Django 3.2.2 on 2022-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnp', '0004_alter_mnp_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnpremark',
            name='commentfile',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='uploadsMNPRemark/%Y/%m/%d/'),
        ),
    ]
