# Generated by Django 3.2.2 on 2022-04-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnp', '0005_alter_mnpremark_commentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnpremark',
            name='commentfile',
            field=models.FileField(blank=True, null=True, upload_to='uploadsMNPRemark/%Y/%m/%d/'),
        ),
    ]
