# Generated by Django 3.2.2 on 2022-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnp', '0006_alter_mnpremark_commentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnpremark',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
