# Generated by Django 3.2.2 on 2022-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnp', '0007_alter_mnpremark_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnp',
            name='UpdateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
