# Generated by Django 3.2.6 on 2022-04-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0002_auto_20220403_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPCRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DPCDef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DPCDef1', to='defi.dpcdef')),
                ('DPCName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DPCName1', to='defi.dpc')),
                ('DefArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DPCArea1', to='defi.dpcarea')),
            ],
        ),
    ]
