# Generated by Django 3.2.6 on 2022-04-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0003_dpcremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCCArea', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TCDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCDef', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dpcremark',
            old_name='DefArea',
            new_name='DPCDefArea',
        ),
        migrations.CreateModel(
            name='TCRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCDef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TCDef1', to='defi.tcdef')),
                ('TCDefArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TCArea1', to='defi.tcarea')),
                ('TCName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TCName1', to='defi.tc')),
            ],
        ),
    ]
