# Generated by Django 3.2.6 on 2022-04-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0008_mcarea_mcdef_mcremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpcarea',
            name='DPCArea',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dpcdef',
            name='DPCDef',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mcarea',
            name='MCArea',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mcdef',
            name='MCDef',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tcarea',
            name='TCCArea',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tcdef',
            name='TCDef',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
