# Generated by Django 3.2.6 on 2022-04-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0009_auto_20220405_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpc',
            name='DPCName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mc',
            name='MCName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tc',
            name='TCName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
