# Generated by Django 3.2.6 on 2022-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0010_auto_20220406_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpcremark',
            name='AddDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcremark',
            name='AddDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tcremark',
            name='AddDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
