# Generated by Django 3.2.2 on 2022-04-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0011_auto_20220406_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpcremark',
            old_name='AddDate',
            new_name='POHDate',
        ),
        migrations.AddField(
            model_name='dpc',
            name='POHDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
