# Generated by Django 3.2.2 on 2022-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0012_auto_20220409_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpc',
            name='POHDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
