# Generated by Django 3.2.2 on 2022-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0013_alter_dpc_pohdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcremark',
            old_name='AddDate',
            new_name='POHDate',
        ),
        migrations.RemoveField(
            model_name='tcremark',
            name='AddDate',
        ),
        migrations.AddField(
            model_name='mc',
            name='POHDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tc',
            name='POHDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tcremark',
            name='POHDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dpcremark',
            name='POHDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
