# Generated by Django 3.2.2 on 2022-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0014_auto_20220409_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcremark',
            name='POHDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
