# Generated by Django 3.2.2 on 2022-04-11 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0015_alter_mcremark_pohdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPCSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
