# Generated by Django 3.2.2 on 2022-04-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0016_dpcsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpcremark',
            name='Section',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='DPCSection1', to='defi.dpcsection'),
        ),
    ]
