# Generated by Django 3.2.2 on 2022-04-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0017_dpcremark_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpcremark',
            name='DPCDef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DPCDef1', to='defi.dpcdef'),
        ),
        migrations.AlterField(
            model_name='dpcremark',
            name='DPCDefArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DPCArea1', to='defi.dpcarea'),
        ),
        migrations.AlterField(
            model_name='dpcremark',
            name='DPCName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DPCName1', to='defi.dpc'),
        ),
        migrations.AlterField(
            model_name='mcremark',
            name='MCDef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MCDef1', to='defi.mcdef'),
        ),
        migrations.AlterField(
            model_name='mcremark',
            name='MCDefArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MCArea1', to='defi.mcarea'),
        ),
        migrations.AlterField(
            model_name='mcremark',
            name='MCName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MCName1', to='defi.mc'),
        ),
        migrations.AlterField(
            model_name='tcremark',
            name='TCDef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TCDef1', to='defi.tcdef'),
        ),
        migrations.AlterField(
            model_name='tcremark',
            name='TCDefArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TCArea1', to='defi.tcarea'),
        ),
        migrations.AlterField(
            model_name='tcremark',
            name='TCName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TCName1', to='defi.tc'),
        ),
    ]
