# Generated by Django 3.2.2 on 2022-04-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defi', '0020_auto_20220411_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc',
            name='Memu',
            field=models.BooleanField(blank=True, default='False'),
        ),
    ]
